version: "3.8"
services:
  backend:
    build: .
    restart: always
    depends_on:
      - mysqldb
    container_name: backend
    ports:
      - "8080:8080"
  mysqldb:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: tiffin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./tiffin.sql:/docker-entrypoint-initdb.d/init.sql